(ns koristiovo.testdata
  "Some data for webapp testing")

(def *sample-interview* 
  {:name "Nikola Plejić"
   :occupation "Developer, developer, developer"
   :image "/img/nikola-plejic.jpg"
   :bio "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae vehicula nulla. Maecenas laoreet cursus hendrerit. Sed pellentesque eros eu mauris aliquam ultricies fermentum odio dictum. Duis consectetur dolor quis quam molestie egestas nec et mi. Pellentesque rhoncus bibendum orci, nec luctus ipsum molestie non. Ut vel neque sapien, vel hendrerit quam. Nunc lorem eros, tristique ac interdum ac, fringilla et eros. Ut scelerisque metus in lorem pulvinar egestas. Suspendisse et dapibus leo. Duis aliquet rhoncus diam, ac lobortis urna suscipit a. Aenean sollicitudin leo ut urna fringilla eget pretium felis auctor. Aliquam erat volutpat. Mauris bibendum tempus varius. Proin placerat lobortis risus et consequat. Donec ut sagittis dolor. Mauris convallis varius justo, non aliquet purus laoreet non. Maecenas a elit et turpis dictum euismod quis a orci. Proin commodo porttitor odio a eleifend. Nam pretium odio ac tortor euismod pellentesque."
   :hardware "Nullam quam lacus, aliquet nec blandit ut, ornare ut lacus. Phasellus ut metus elit, in mollis nunc. Cras vestibulum, elit vitae venenatis facilisis, sem nunc hendrerit mauris, sit amet lacinia mi tortor ut lectus. Phasellus sodales, ante ac dapibus laoreet, nisl odio interdum turpis, cursus suscipit erat lacus nec nibh. Morbi porta dui et urna viverra tempus. Donec ultricies nisi vel nibh dignissim in auctor nulla vestibulum. In elementum convallis mollis. Sed velit felis, ornare sit amet egestas sit amet, dignissim vitae nibh. Cras vel metus ligula, quis ornare ante. Vestibulum consequat pharetra tortor, in dictum purus rhoncus vel. Vestibulum bibendum, tellus eget pulvinar consequat, justo mauris porttitor sapien, id mattis lorem eros nec ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dictum metus in est convallis laoreet. Nam sit amet arcu diam, id dignissim sem. Nullam felis lorem, pellentesque eu consectetur ut, dapibus et purus. Aenean hendrerit tortor in purus tincidunt dignissim sit amet eu tellus. Nulla tempus nunc eget lorem pulvinar ullamcorper. Maecenas cursus tempor risus a dapibus."
   :software "Proin eu metus dui. In hac habitasse platea dictumst. Ut ornare, magna quis commodo vulputate, purus mauris blandit augue, at molestie mi mauris vitae lectus. Donec accumsan venenatis vulputate. Proin odio metus, blandit vel pretium sit amet, faucibus et dui. Praesent congue pretium rutrum. Fusce at nisi felis. Vivamus enim velit, porta in malesuada feugiat, volutpat vitae leo. In interdum pellentesque massa vitae eleifend. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam eget porta urna. Proin tincidunt nisl vitae magna ultricies dapibus. Mauris at pharetra elit."
   :dream-setup "Suspendisse turpis orci, commodo faucibus ornare non, iaculis ac magna. Proin id justo dignissim tortor auctor aliquam. Nulla facilisis imperdiet placerat. Cras quis orci neque, a scelerisque leo. Maecenas facilisis purus non neque ultricies sodales. Nullam vitae velit tellus, ut convallis sapien. Phasellus ante lectus, rutrum et lacinia sed, cursus at ipsum. Suspendisse vel sapien id lorem mollis gravida. Duis eu metus in orci pellentesque accumsan. Donec luctus faucibus molestie. Nullam ac metus dui, in rhoncus quam. Quisque eros turpis, pulvinar vel pharetra a, bibendum at purus. Suspendisse fringilla lorem sagittis nisi ultrices porttitor. Sed gravida erat et sapien volutpat molestie. Aliquam dolor sapien, elementum quis scelerisque a, mattis eu risus. Nunc at ante tellus. Donec sit amet massa vel ligula vulputate lobortis. Donec venenatis gravida fermentum. In hac habitasse platea dictumst."})

